function singularity_list = get_singularity_list()
% This is a dummy functiont that returns the list with available types of
% singularities in the classification functions. 

% Check with mapp_str2int

singularity_list = {'source', ...
                    'sink', ...
                    '2-1-saddle',...
                    '1-2-saddle',... 
                    'spiral-source',... 
                    'spiral-sink',...
                    '2-1-spiral-saddle', ...
                    '1-2-spiral-saddle', ...
                    'source-po',...
                    'sink-po',...
                    'saddle-po',...
                    'twisted-po',...
                    'spiral-source-po',...
                    'spiral-sink-po', ...
                    '1-1-0-saddle', ... % unclassified
                    'nan'}; % unclassified
                
end % function get_singularity_list()
